/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package editor.de.imgens;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.FlatArcDarkIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatArcIJTheme;
import static editor.de.imgens.Geral.imgbufferedEditada;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ERNESTO ARGENTINA
 */
public class Editor extends javax.swing.JFrame {

    String path = "";
    private BufferedImage imgbuffered = null;

    /**
     * Creates new form Home
     */
    public Editor() {
        initComponents();
//        painelEdicaoImagem.add(new PainelImagem());
        setSize(1000, 600);
        
        try {
            UIManager.setLookAndFeel( new FlatLightLaf() );
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btCaneta = new javax.swing.JButton();
        btFlipH = new javax.swing.JButton();
        btRotate = new javax.swing.JButton();
        btFlipV = new javax.swing.JButton();
        btCrop = new javax.swing.JButton();
        btTranslateLrft = new javax.swing.JButton();
        btTranslateRight = new javax.swing.JButton();
        btTranslateUp = new javax.swing.JButton();
        btTranslateTop = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfComprimento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfLargura = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        btCaneta2 = new javax.swing.JButton();
        btCaneta3 = new javax.swing.JButton();
        btCaneta4 = new javax.swing.JButton();
        btCaneta5 = new javax.swing.JButton();
        btCaneta6 = new javax.swing.JButton();
        btCaneta7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tfTamanhoPonta = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        painelEdicaoImagem = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Comprimento");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Caneta");

        btCaneta.setBackground(new java.awt.Color(255, 0, 0));
        btCaneta.setForeground(new java.awt.Color(255, 51, 51));
        btCaneta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editor/de/imgens/icons/brush-outline_30.png"))); // NOI18N
        btCaneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCanetaActionPerformed(evt);
            }
        });

        btFlipH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editor/de/imgens/icons/flip-2-outline.png"))); // NOI18N
        btFlipH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFlipHActionPerformed(evt);
            }
        });

        btRotate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editor/de/imgens/icons/corner-up-right-outline.png"))); // NOI18N
        btRotate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRotateActionPerformed(evt);
            }
        });

        btFlipV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editor/de/imgens/icons/flip-outline.png"))); // NOI18N
        btFlipV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFlipVActionPerformed(evt);
            }
        });

        btCrop.setBackground(new java.awt.Color(255, 0, 0));
        btCrop.setForeground(new java.awt.Color(255, 51, 51));
        btCrop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editor/de/imgens/icons/crop-outline.png"))); // NOI18N
        btCrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCropActionPerformed(evt);
            }
        });

        btTranslateLrft.setBackground(new java.awt.Color(255, 255, 255));
        btTranslateLrft.setForeground(new java.awt.Color(255, 51, 51));
        btTranslateLrft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editor/de/imgens/icons/arrow-circle-left-outline_30.png"))); // NOI18N
        btTranslateLrft.setIconTextGap(1);
        btTranslateLrft.setMaximumSize(new java.awt.Dimension(30, 30));
        btTranslateLrft.setMinimumSize(new java.awt.Dimension(20, 20));
        btTranslateLrft.setPreferredSize(new java.awt.Dimension(30, 30));
        btTranslateLrft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTranslateLrftActionPerformed(evt);
            }
        });

        btTranslateRight.setBackground(new java.awt.Color(255, 255, 255));
        btTranslateRight.setForeground(new java.awt.Color(255, 51, 51));
        btTranslateRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editor/de/imgens/icons/arrow-circle-right-outline_30.png"))); // NOI18N
        btTranslateRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTranslateRightActionPerformed(evt);
            }
        });

        btTranslateUp.setBackground(new java.awt.Color(255, 255, 255));
        btTranslateUp.setForeground(new java.awt.Color(255, 51, 51));
        btTranslateUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editor/de/imgens/icons/arrow-circle-up-outline_30.png"))); // NOI18N
        btTranslateUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTranslateUpActionPerformed(evt);
            }
        });

        btTranslateTop.setBackground(new java.awt.Color(255, 255, 255));
        btTranslateTop.setForeground(new java.awt.Color(255, 51, 51));
        btTranslateTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editor/de/imgens/icons/arrow-circle-down-outline_30.png"))); // NOI18N
        btTranslateTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTranslateTopActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Translação");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Scale");

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Comprimento");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("largura");

        jButton4.setText("Scale");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btCaneta2.setBackground(new java.awt.Color(255, 255, 0));
        btCaneta2.setForeground(new java.awt.Color(255, 51, 51));
        btCaneta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCaneta2ActionPerformed(evt);
            }
        });

        btCaneta3.setBackground(new java.awt.Color(0, 204, 51));
        btCaneta3.setForeground(new java.awt.Color(255, 51, 51));
        btCaneta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCaneta3ActionPerformed(evt);
            }
        });

        btCaneta4.setBackground(new java.awt.Color(255, 255, 255));
        btCaneta4.setForeground(new java.awt.Color(255, 51, 51));
        btCaneta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCaneta4ActionPerformed(evt);
            }
        });

        btCaneta5.setBackground(new java.awt.Color(0, 0, 255));
        btCaneta5.setForeground(new java.awt.Color(255, 51, 51));
        btCaneta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCaneta5ActionPerformed(evt);
            }
        });

        btCaneta6.setBackground(new java.awt.Color(0, 0, 0));
        btCaneta6.setForeground(new java.awt.Color(255, 51, 51));
        btCaneta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCaneta6ActionPerformed(evt);
            }
        });

        btCaneta7.setBackground(new java.awt.Color(255, 0, 0));
        btCaneta7.setForeground(new java.awt.Color(255, 51, 51));
        btCaneta7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCaneta7ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editor/de/imgens/icons/minus-circle-outline.png"))); // NOI18N

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editor/de/imgens/icons/plus-circle-outline.png"))); // NOI18N

        tfTamanhoPonta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfTamanhoPontaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btFlipH, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFlipV, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRotate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCrop, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfComprimento)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfLargura)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btTranslateLrft, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btTranslateTop, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btTranslateRight, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btTranslateUp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(53, 53, 53))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTamanhoPonta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCaneta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btCaneta2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btCaneta3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btCaneta4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btCaneta5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btCaneta6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btCaneta7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, 0)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfTamanhoPonta)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btCaneta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btCaneta2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btCaneta3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btCaneta4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btCaneta5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btCaneta6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btCaneta7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btFlipH)
                            .addComponent(btFlipV))
                        .addComponent(btCrop, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btRotate, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btTranslateUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btTranslateLrft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btTranslateRight, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btTranslateTop, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel2);

        painelEdicaoImagem.setBackground(new java.awt.Color(255, 255, 255));
        painelEdicaoImagem.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                painelEdicaoImagemMouseMoved(evt);
            }
        });
        painelEdicaoImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                painelEdicaoImagemMouseReleased(evt);
            }
        });
        painelEdicaoImagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                painelEdicaoImagemKeyPressed(evt);
            }
        });
        painelEdicaoImagem.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane1.setViewportView(painelEdicaoImagem);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        getContentPane().add(jPanel1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editor/de/imgens/icons/file-outline.png"))); // NOI18N
        jMenu2.setText("File");

        jMenuItem3.setText("Novo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem2.setText("Salvar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editor/de/imgens/icons/edit-outline.png"))); // NOI18N
        jMenu3.setText("Edit");

        jMenuItem4.setText("Undo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editor/de/imgens/icons/funnel-outline.png"))); // NOI18N
        jMenu4.setText("Filtros");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem5.setText("Preto branco");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem6.setText("Outro");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
    este metodo serve para ler a imagem
     */
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setDialogTitle("Escolha o ficheiro");
//         filtramos aqui o tipo de ficheiro por seleccionar
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images", "jpg", "png", "gif");
        file.addChoosableFileFilter(filter);

        int result = file.showSaveDialog(null);
        /*
        se tiver sido seleccionado um ficheiro ele ira salvar na variavel Geral.path
        o caminho do ficheiro seleccionado
         */
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            path = selectedFile.getAbsolutePath();
            actualizarPainelImgem();
            Geral.path = path; //salvar o caminho na variavel Geral.path

            painelEdicaoImagem.add(new PainelImagem());
            repaint();
        } else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("Nenhum ficheiro seleccionado");
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images", "jpg", "png", "gif");
        fileChooser.addChoosableFileFilter(filter);

        int result = fileChooser.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            path = selectedFile.getAbsolutePath();
//            lbImagem.setText("");
////            lbImagem.setIcon(ResizeImage(path));
//            lbImagem.setIcon(ResizeImageBuffered(path));
            try {
                File file = new File(path);
                ImageIO.write(Geral.imgbufferedEditada, "jpg", file);
                JOptionPane.showMessageDialog(null, "Salvo com sucesso");
                actualizarPainelImgem();

                Geral.imgbufferedEditada = null;
                Geral.imgbuffered = null;

            } catch (Exception e) {

            }
        } else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("Nenhum ficheiro seleccionado");
        }

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btCanetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCanetaActionPerformed
        // TODO add your handling code here:
        if (btCaneta.getText().equals("on")) {
            Geral.pintar = false;
            btCaneta.setText("");
            btCaneta.setBackground(Color.red);
        } else {
            Geral.pintar = true;
            btCaneta.setText("on");
            btCaneta.setBackground(Color.GREEN);
        }
    }//GEN-LAST:event_btCanetaActionPerformed

    private void tfTamanhoPontaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTamanhoPontaKeyReleased
        // TODO add your handling code here:
        if (tfTamanhoPonta.getText().equals("")) {
            Geral.tamanhoPonta = 10;
        } else {
            Geral.tamanhoPonta = Integer.parseInt(tfTamanhoPonta.getText());
        }
    }//GEN-LAST:event_tfTamanhoPontaKeyReleased

    private void painelEdicaoImagemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_painelEdicaoImagemKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_painelEdicaoImagemKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        if (btCaneta.getText().equals("on")) {
            Geral.pintar = false;
            btCaneta.setText("off");
            btCaneta.setForeground(Color.red);
        } else {
            Geral.pintar = true;
            btCaneta.setText("on");
            btCaneta.setForeground(Color.GREEN);
        }
        System.out.println("pressed");
    }//GEN-LAST:event_formKeyPressed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Geral.imgbufferedEditada = Geral.imgbuffered;
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btFlipHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFlipHActionPerformed
        // TODO add your handling code here:
        int h = Geral.imgbufferedEditada.getHeight();
        int w = Geral.imgbufferedEditada.getWidth();
        Geral.imgbufferedauxiliar = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2ImageAu = Geral.imgbufferedauxiliar.createGraphics();
        AffineTransform at = new AffineTransform();
        at.setToTranslation(w, 0);
        at.scale(-1, 1);
//        g2ImageAu.setTransform(at);
        g2ImageAu.drawImage(imgbufferedEditada, at, this);
        PainelImagem.g2Image.fillRect(0, 0, w, h);
        PainelImagem.g2Image.drawImage(Geral.imgbufferedauxiliar, 0, 0, this);
        repaint();
    }//GEN-LAST:event_btFlipHActionPerformed

    private void btRotateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRotateActionPerformed
        // TODO add your handling code here:
        int h = Geral.imgbufferedEditada.getHeight();
        int w = Geral.imgbufferedEditada.getWidth();
        Geral.imgbufferedauxiliar = new BufferedImage(h, w, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2ImageAu = Geral.imgbufferedauxiliar.createGraphics();
        AffineTransform at = new AffineTransform();
        at.setToTranslation(h, 0);
        at.rotate(Math.toRadians(90));
        g2ImageAu.drawImage(imgbufferedEditada, at, this);

        imgbufferedEditada = new BufferedImage(h, w, BufferedImage.TYPE_INT_ARGB);
        PainelImagem.g2Image = imgbufferedEditada.createGraphics();
        PainelImagem.g2Image.drawImage(Geral.imgbufferedauxiliar, 0, 0, this);
        repaint();
    }//GEN-LAST:event_btRotateActionPerformed

    private void btFlipVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFlipVActionPerformed
        // TODO add your handling code here:
        int altura = Geral.imgbufferedEditada.getHeight();
        int comprimento = Geral.imgbufferedEditada.getWidth();
        Geral.imgbufferedauxiliar = new BufferedImage(comprimento, altura, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2ImageAu = Geral.imgbufferedauxiliar.createGraphics();
        AffineTransform at = new AffineTransform();
        at.setToTranslation(0, altura);
        at.scale(1, -1);
//        g2ImageAu.setTransform(at);
        g2ImageAu.drawImage(imgbufferedEditada, at, this);
        PainelImagem.g2Image.drawImage(Geral.imgbufferedauxiliar, 0, 0, this);
        repaint();
    }//GEN-LAST:event_btFlipVActionPerformed

    private void btCropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCropActionPerformed
        // TODO add your handling code here:
        Geral.crop = true;
        repaint();
    }//GEN-LAST:event_btCropActionPerformed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        repaint();
        System.out.println("dd");
    }//GEN-LAST:event_formMouseReleased

    private void painelEdicaoImagemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelEdicaoImagemMouseReleased
        // TODO add your handling code here:
        repaint();
        System.out.println("ddp");
    }//GEN-LAST:event_painelEdicaoImagemMouseReleased

    private void painelEdicaoImagemMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelEdicaoImagemMouseMoved
        // TODO add your handling code here:
        repaint();
        System.out.println("mouse moved");

    }//GEN-LAST:event_painelEdicaoImagemMouseMoved

    private void btTranslateLrftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTranslateLrftActionPerformed
        // TODO add your handling code here:
 int h = Geral.imgbufferedEditada.getHeight();
        int w = Geral.imgbufferedEditada.getWidth();
        Geral.imgbufferedauxiliar = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2ImageAu = Geral.imgbufferedauxiliar.createGraphics();
        AffineTransform at = new AffineTransform();
        at.setToTranslation(-2, 0);
        Geral.xTranslacao += 1;
        g2ImageAu.fillRect(0, 0, w, h);
        g2ImageAu.drawImage(imgbufferedEditada, at, this);
        PainelImagem.g2Image.drawImage(Geral.imgbufferedauxiliar, 0, 0, this);
        repaint();

    }//GEN-LAST:event_btTranslateLrftActionPerformed

    private void btTranslateRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTranslateRightActionPerformed
        // TODO add your handling code here:
        int h = Geral.imgbufferedEditada.getHeight();
        int w = Geral.imgbufferedEditada.getWidth();
        Geral.imgbufferedauxiliar = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2ImageAu = Geral.imgbufferedauxiliar.createGraphics();
        AffineTransform at = new AffineTransform();
        at.setToTranslation(2, 0);
        Geral.xTranslacao += 1;
        g2ImageAu.fillRect(0, 0, w, h);
        g2ImageAu.drawImage(imgbufferedEditada, at, this);
        PainelImagem.g2Image.drawImage(Geral.imgbufferedauxiliar, 0, 0, this);
        repaint();
    }//GEN-LAST:event_btTranslateRightActionPerformed

    private void btTranslateUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTranslateUpActionPerformed
        // TODO add your handling code here:
         int h = Geral.imgbufferedEditada.getHeight();
        int w = Geral.imgbufferedEditada.getWidth();
        Geral.imgbufferedauxiliar = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2ImageAu = Geral.imgbufferedauxiliar.createGraphics();
        AffineTransform at = new AffineTransform();
        at.setToTranslation(0, -2);
        g2ImageAu.fillRect(0, 0, w, h);
        g2ImageAu.drawImage(imgbufferedEditada, at, this);
        PainelImagem.g2Image.drawImage(Geral.imgbufferedauxiliar, 0, 0, this);
        repaint();
    }//GEN-LAST:event_btTranslateUpActionPerformed

    private void btTranslateTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTranslateTopActionPerformed
        // TODO add your handling code here:int h = Geral.imgbufferedEditada.getHeight();
        int h = Geral.imgbufferedEditada.getHeight();
        int w = Geral.imgbufferedEditada.getWidth();
        Geral.imgbufferedauxiliar = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2ImageAu = Geral.imgbufferedauxiliar.createGraphics();
        AffineTransform at = new AffineTransform();
//        mover a imagem pra baixo
        at.setToTranslation(0, 2);
        g2ImageAu.fillRect(0, 0, w, h);
        g2ImageAu.drawImage(imgbufferedEditada, at, this);
        PainelImagem.g2Image.drawImage(Geral.imgbufferedauxiliar, 0, 0, this);
        repaint();
    }//GEN-LAST:event_btTranslateTopActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Geral.comprimento = Integer.parseInt(tfComprimento.getText());
        Geral.largura = Integer.parseInt(tfLargura.getText());
        ScaleImage();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btCaneta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCaneta2ActionPerformed
        // TODO add your handling code here:
        Geral.corPaint="amarelo";
        btCaneta.setBackground(Color.YELLOW);
    }//GEN-LAST:event_btCaneta2ActionPerformed

    private void btCaneta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCaneta3ActionPerformed
        // TODO add your handling code here:
        Geral.corPaint="verde";
        btCaneta.setBackground(Color.GREEN);
    }//GEN-LAST:event_btCaneta3ActionPerformed

    private void btCaneta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCaneta4ActionPerformed
        // TODO add your handling code here:
        Geral.corPaint="branco";
        btCaneta.setBackground(Color.WHITE);
    }//GEN-LAST:event_btCaneta4ActionPerformed

    private void btCaneta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCaneta5ActionPerformed
        // TODO add your handling code here:
        Geral.corPaint="azul";
        btCaneta.setBackground(Color.BLUE);
    }//GEN-LAST:event_btCaneta5ActionPerformed

    private void btCaneta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCaneta6ActionPerformed
        // TODO add your handling code here:
        Geral.corPaint="preto";
        btCaneta.setBackground(Color.BLACK);
    }//GEN-LAST:event_btCaneta6ActionPerformed

    private void btCaneta7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCaneta7ActionPerformed
        // TODO add your handling code here:
        Geral.corPaint="vermelho";
        btCaneta.setBackground(Color.RED);
    }//GEN-LAST:event_btCaneta7ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
            pretoBranco();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
         pretoBrancofiltro();
        repaint();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }

  
        try {
            UIManager.setLookAndFeel( new FlatArcIJTheme());
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        
        
        
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCaneta;
    private javax.swing.JButton btCaneta2;
    private javax.swing.JButton btCaneta3;
    private javax.swing.JButton btCaneta4;
    private javax.swing.JButton btCaneta5;
    private javax.swing.JButton btCaneta6;
    private javax.swing.JButton btCaneta7;
    private javax.swing.JButton btCrop;
    private javax.swing.JButton btFlipH;
    private javax.swing.JButton btFlipV;
    private javax.swing.JButton btRotate;
    private javax.swing.JButton btTranslateLrft;
    private javax.swing.JButton btTranslateRight;
    private javax.swing.JButton btTranslateTop;
    private javax.swing.JButton btTranslateUp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel painelEdicaoImagem;
    private javax.swing.JTextField tfComprimento;
    private javax.swing.JTextField tfLargura;
    private javax.swing.JTextField tfTamanhoPonta;
    // End of variables declaration//GEN-END:variables

    private Icon ResizeImage(String path) {
        ImageIcon MyImage = new ImageIcon(path);

        Image img = MyImage.getImage();

//        Image newImage = img.getScaledInstance(lbImagem.getWidth(), lbImagem.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon image = new ImageIcon(newImage);
//        return image;
        return null;

    }

    private Icon ResizeImageBuffered(String path) {
//        ImageIcon MyImage = new ImageIcon(path);
        File file = new File(path);
        imgbuffered = null;
        try {
            imgbuffered = ImageIO.read(file);
        } catch (Exception e) {
            System.out.println("erro: " + e);
        }

//        Image newImage = imgbuffered.getScaledInstance(lbImagem.getWidth(), lbImagem.getHeight(), 1);
//        ImageIcon image = new ImageIcon(newImage);
//        return image;
        return null;

    }





    private void ScaleImage() {
 
        int w = Geral.comprimento;
        int h = Geral.largura;
        Image newImage = Geral.imgbufferedEditada.getScaledInstance(w, h, 1);
        
        Geral.imgbufferedauxiliar = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2ImageAu = Geral.imgbufferedauxiliar.createGraphics();
        g2ImageAu.drawImage(imgbufferedEditada, 0, 0, w, h, Geral.xInicial, Geral.yInicial, Geral.xFinal, Geral.yFinal, this);

        imgbufferedEditada = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
        PainelImagem.g2Image = imgbufferedEditada.createGraphics();
        PainelImagem.g2Image.drawImage(newImage, 0, 0, this);
        repaint(0);

    }

    /*
    este metodo filtra a imagem em preto branco
     */
    private void pretoBranco() {
        int altura = Geral.imgbufferedEditada.getHeight();
        int comprimento = Geral.imgbufferedEditada.getWidth();

        for (int y = 0; y < altura; y++) {
            for (int x = 0; x < comprimento; x++) {
                int p = Geral.imgbufferedEditada.getRGB(x, y);

                int a = (p >> 24) & 0xff;
                int r = (p >> 16) & 0xff;
                int g = (p >> 8) & 0xff;
                int b = p & 0xff;

//                media
                int avg = (r + g + b) / 3;

                p = (a << 24) | (avg << 16) | (avg << 8) | avg;
                Geral.imgbufferedEditada.setRGB(x, y, p);
            }
        }
        repaint();
    }

    private void pretoBrancofiltro() {
        int altura = Geral.imgbufferedEditada.getHeight();
        int comprimento = Geral.imgbufferedEditada.getWidth();

        for (int y = 0; y < altura; y++) {
            for (int x = 0; x < comprimento; x++) {
                int p = Geral.imgbufferedEditada.getRGB(x, y);

                int a = (p >> 24) & 0xff;
                int r = (p >> 16) & 0xff;
                int g = (p >> 8) & 0xff;
                int b = p & 0xff;

//                media
                int avg = (r + g + b) / 3;

                p = (a << 20) | (avg << 16) | (avg << 8) | avg;
//                Geral.imgbufferedEditada.setRGB(x, y, p);
                Geral.imgbufferedEditada.setRGB(x, y, new Color(r, g, b).getRGB());
            }
        }
        repaint();
    }

    private void actualizarPainelImgem() {
        Geral.imgbufferedEditada = null;
        Geral.imgbuffered = null;
        Geral.imgbufferedauxiliar = null;
        painelEdicaoImagem.removeAll();
        painelEdicaoImagem.repaint();
        painelEdicaoImagem.revalidate();
    }

}
